### ISSUE TITLE
Data Set used for testing

### ISSUE THREAD

**Issue by KAMRANMEHBOOB** [SDN-Security/TENNISON#6]
Which Data Set is used by the tennison framework for the results given?

**Comment by lyndon160** [comment]
I assume you are refering to the results in the paper?

The paper details that no Data set was used, but rather a series of executed processes that produce network traffic. A DASH video stream, some IPerfs, etc.

There are examples available in the tools folder.

The main reason this is used instead of a data set is that these are produced across the network, and dynamically change to the status of the network (TCP & UDP dropped packets). Also replaying a data set is usually just done at the core of the network, this is not very good when testing large scale networks.
